name: lint
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
    awesome-lint:
      strategy:
        fail-fast: false
        matrix:
          files:
            - "README.md"
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v2
          with:
            persist-credentials: false
            fetch-depth: 0
        #- name: asdf_install
        #  uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa
        #  with:
        #    node-version: 12.x
        - name: "linting: ${{ matrix.files }}"
          run: npx -y awesome-lint ${{ matrix.files }}
    awesome-bot:
      strategy:
        fail-fast: false
        matrix:
          files:
            - "README.md"
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v2.0.0
          with:
            fetch-depth: 0
        - name: "setup ruby"
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.0.1
            bundler-cache: true
        - name: "install awesome-bot"
          run: gem install awesome_bot
        - name: "linting: ${{ matrix.files }}"
          run: awesome_bot --allow-redirect --white-list https://github.com/EanNewton/Awesome-Reading-List ${{ matrix.files }} 
